let user,products=[],type='general',qty={};const money=n=>'$'+Number(n).toLocaleString('ja-JP');
async function api(url,opt){const r=await fetch(url,opt);if(r.status===401){location.href='/login.html';throw Error('login')}const d=await r.json();if(!r.ok)throw Error(d.error||'エラー');return d}
async function init(){const me=await api('/api/me');user=me.user;staffName.textContent=`${user.display_name}（${user.username}）`;roleBadge.textContent=user.role==='admin'?'管理者':'スタッフ';if(user.role==='admin')adminLink.classList.remove('hidden');const d=await api('/api/products');products=d.products;render()}
function render(){const groups={};for(const p of products)(groups[p.category]??=[]).push(p);document.querySelector('#products').innerHTML=Object.entries(groups).map(([cat,ps])=>`<section class="card product-group"><h3>${esc(cat)}</h3>${ps.map(p=>{const q=qty[p.id]||0;const unit=type!=='general'&&p.pd_ems_half?Math.floor(p.price/2):p.price;return `<div class="product"><div><strong>${esc(p.name)}</strong>${type!=='general'&&p.pd_ems_half?'<div class="discount">PD/EMS 50%対象</div>':''}</div><span class="price">${money(unit)}</span><div class="qty"><button data-minus="${p.id}">−</button><input data-input="${p.id}" value="${q}" inputmode="numeric"><button data-plus="${p.id}">＋</button></div><span>${money(unit*q)}</span></div>`}).join('')}</section>`).join('');document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>setQ(+b.dataset.minus,(qty[b.dataset.minus]||0)-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>setQ(+b.dataset.plus,(qty[b.dataset.plus]||0)+1));document.querySelectorAll('[data-input]').forEach(i=>i.onchange=()=>setQ(+i.dataset.input,+i.value));updateTotal()}
function setQ(id,q){const p=products.find(x=>x.id===id);q=Math.max(0,Math.floor(Number(q)||0));if(p.max_qty!==null)q=Math.min(p.max_qty,q);qty[id]=q;render()}
function updateTotal(){let t=0;for(const p of products){const q=qty[p.id]||0;const u=type!=='general'&&p.pd_ems_half?Math.floor(p.price/2):p.price;t+=u*q}total.textContent=money(t);return t}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]))}
function selected(){return products.filter(p=>(qty[p.id]||0)>0).map(p=>{const q=qty[p.id],u=type!=='general'&&p.pd_ems_half?Math.floor(p.price/2):p.price;return {product_id:p.id,name:p.name,quantity:q,unit:u,subtotal:u*q}})}
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.type;render()};copyBill.onclick=async()=>{const items=selected();const t=updateTotal();if(!items.length)return;const text=['【RedLine Customs】',`顧客区分：${type.toUpperCase()}`,...items.map(x=>`${x.name} × ${x.quantity}：${money(x.subtotal)}`),`合計：${money(t)}`].join('\n');output.value=text;await navigator.clipboard.writeText(text)};copyThanks.onclick=async()=>{const text='この度はRedLine Customsをご利用いただき、ありがとうございました。';output.value=text;await navigator.clipboard.writeText(text)};saveLog.onclick=async()=>{try{const items=selected();if(!items.length)return alert('商品を1つ以上選択してください');const d=await api('/api/worklogs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customer_type:type,items:items.map(x=>({product_id:x.product_id,quantity:x.quantity}))})});alert(`作業履歴を保存しました。\n合計：${money(d.total)}`)}catch(e){alert(e.message)}};logoutBtn.onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.href='/login.html'};init().catch(()=>location.href='/login.html');
